name = "bfrs-staging"
main = "dist/worker/index.js"
compatibility_date = "2024-09-01"
workers_dev = true

# Serve your built Vite assets (adjust if your build path differs)
assets = { directory = "dist/client" }

# Default D1 binding (can be overridden per env if you want)
[[d1_databases]]
binding = "DB"
database_name = "bfrs-staging"
database_id = "8b30ad54-35d9-45e3-96e6-003e7772f0b5"

# Global vars (applies to wrangler dev)
[vars]
DEV_AUTH = "true"
DEV_USER_EMAIL = "dev@example.com"
DEV_USER_NAME = "Dev User"
DEV_USER_ID = "1"

[env.staging]
name = "bfrs-staging"
workers_dev = true

[env.staging.vars]
# Not secret, fine to live as VARs
AWS_SES_REGION = "us-east-2"
SENDER_FROM = "Brain Fog Recovery Source <nonprofit@mentalhealthketo.com>"
BUILD_ID = "staging"
# TEMP: because some routes still check this, set a dummy value to bypass the old SendGrid check
SENDGRID_API_KEY = "dummy"
# Enable dev auth on staging too
DEV_AUTH = "true"
DEV_USER_EMAIL = "demo@client.com"
DEV_USER_NAME = "Demo User"
DEV_USER_ID = "3324e3f1de03a6a2b19ff09d9853d828"
